import { Innertube } from 'youtubei.js';
import logger from '../utils/logger.js';

// CONFIGURATION
const CONFIG = {
  CACHE_TTL:             60 * 60 * 1000,
  CACHE_MAX_SIZE:        500,
  CACHE_FAILURE_TTL:     5  * 60 * 1000,
  FETCH_TIMEOUT:         20_000,
  CONCURRENT_LIMIT:      3,
  WORD_LIMIT:            4000,
  SUMMARIZATION_THRESHOLD: 4000,
  MIN_TRANSCRIPT_LENGTH: 50,
  MIN_DESCRIPTION_LENGTH: 50,
  PREFERRED_LANGUAGES: ['en', 'en-US', 'en-GB', 'en-CA', 'en-AU'],
};

class LRUCache {
  constructor(maxSize) {
    this.maxSize = maxSize;
    this.cache   = new Map();
  }

  get(key) {
    if (!this.cache.has(key)) return null;
    const value = this.cache.get(key);
    this.cache.delete(key);
    this.cache.set(key, value);
    if (Date.now() > value.expiresAt) {
      this.cache.delete(key);
      return null;
    }
    return value.data;
  }

  set(key, data, ttl) {
    if (this.cache.has(key)) this.cache.delete(key);
    if (this.cache.size >= this.maxSize) {
      this.cache.delete(this.cache.keys().next().value);
    }
    this.cache.set(key, { data, expiresAt: Date.now() + ttl });
  }

  has(key)  { return this.get(key) !== null; }
  size()    { return this.cache.size; }
  clear()   { this.cache.clear(); }
}

const transcriptCache = new LRUCache(CONFIG.CACHE_MAX_SIZE);
const failureCache    = new LRUCache(CONFIG.CACHE_MAX_SIZE);

let ytClient          = null;
let clientInitPromise = null;

// YOUTUBE CLIENT SINGLETON
async function getYTClient() {
  if (ytClient) return ytClient;
  if (clientInitPromise) return clientInitPromise;

  clientInitPromise = Innertube.create({
    generate_session_locally: true,
    lang:     'en',
    location: 'US',
  })
    .then((client) => {
      ytClient = client;
      logger?.info?.('YouTube client initialised');
      return client;
    })
    .catch((err) => {
      clientInitPromise = null;
      throw err;
    });

  return clientInitPromise;
}

// extract video ID from various YouTube URL formats
export function extractVideoId(url) {
  if (!url || typeof url !== 'string') return null;

  const patterns = [
    /(?:youtube\.com\/watch\?.*v=)([a-zA-Z0-9_-]{11})/,
    /(?:youtu\.be\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube-nocookie\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /^([a-zA-Z0-9_-]{11})$/,
  ];

  for (const p of patterns) {
    const m = url.match(p);
    if (m) return m[1];
  }
  return null;
}

function withTimeout(promise, ms, label = 'Operation') {
  return Promise.race([
    promise,
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`${label} timed out after ${ms}ms`)), ms)
    ),
  ]);
}

async function parallelLimit(tasks, limit) {
  const results = [];
  const running = [];

  for (const task of tasks) {
    const p = Promise.resolve().then(() => task());
    results.push(p);

    if (limit <= tasks.length) {
      const e = p.finally(() => running.splice(running.indexOf(e), 1));
      running.push(e);
      if (running.length >= limit) await Promise.race(running);
    }
  }

  return Promise.allSettled(results);
}

// CAPTION TRACK SELECTION
function selectCaptionTrack(tracks) {
  if (!Array.isArray(tracks) || tracks.length === 0) return null;

  for (const lang of CONFIG.PREFERRED_LANGUAGES) {
    const t = tracks.find(t => t.language_code === lang && t.kind !== 'asr');
    if (t) return { track: t, language: lang, isAutoGenerated: false };
  }

  for (const lang of CONFIG.PREFERRED_LANGUAGES) {
    const t = tracks.find(t => t.language_code === lang && t.kind === 'asr');
    if (t) return { track: t, language: lang, isAutoGenerated: true };
  }

  const enTrack = tracks.find(t => t.language_code?.startsWith('en'));
  if (enTrack) {
    return {
      track: enTrack,
      language: enTrack.language_code,
      isAutoGenerated: enTrack.kind === 'asr',
    };
  }

  return {
    track: tracks[0],
    language: tracks[0].language_code,
    isAutoGenerated: tracks[0].kind === 'asr',
  };
}

// CDN TRANSCRIPT FETCH
async function fetchCaptionJSON3(baseUrl) {
  const url = `${baseUrl}&fmt=json3`;
  const response = await withTimeout(fetch(url), CONFIG.FETCH_TIMEOUT, 'Caption CDN fetch');

  if (!response.ok) throw new Error(`Caption CDN returned HTTP ${response.status}`);
  return response.json();
}

function json3EventsToText(events) {
  if (!Array.isArray(events) || events.length === 0) return '';

  return events
    .filter(e => Array.isArray(e.segs) && e.segs.length > 0)
    .map(e => e.segs.map(seg => seg?.utf8 ?? '').join('').replace(/\n/g, ' ').trim())
    .filter(Boolean)
    .join(' ');
}

// TEXT CLEANING
function cleanTranscriptText(text) {
  if (!text) return '';

  return text
    .replace(/\[(Music|Applause|Laughter|Sound Effect|Música)\]/gi, '')
    .replace(/\[[^\]]{1,40}\]:\s*/g, '')
    .replace(/\[(?!Chapter|Section|Part)[^\]]{1,20}\]/g, '')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[ \t]{2,}/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .split('\n')
    .filter(line => line.trim().length > 2)
    .join('\n')
    .trim();
}

function deduplicateText(text) {
  if (!text) return '';

  const sentences = text
    .replace(/([.!?])\s+/g, '$1\n')
    .split('\n')
    .map(s => s.trim())
    .filter(Boolean);

  const seen = new Set();
  const unique = [];

  for (const sentence of sentences) {
    const key = sentence.toLowerCase().replace(/[^a-z0-9\s]/g, '').replace(/\s+/g, ' ').trim();
    if (key.length > 10 && seen.has(key)) continue;
    seen.add(key);
    unique.push(sentence);
  }

  return unique.join(' ').trim();
}

// MAIN EXPORT
export async function fetchTranscriptSafe(videoUrl) {
  const videoId = extractVideoId(videoUrl);
  if (!videoId) return null;

  const failKey = `failure:${videoId}`;
  if (failureCache.has(failKey)) return null;

  const cached = transcriptCache.get(videoId);
  if (cached) return cached;

  try {
    const yt = await getYTClient();

    const info = await withTimeout(yt.getInfo(videoId), CONFIG.FETCH_TIMEOUT, 'getInfo');

    const captionTracks = info.captions?.caption_tracks ?? [];
    if (captionTracks.length === 0) {
      failureCache.set(failKey, true, CONFIG.CACHE_FAILURE_TTL);
      return null;
    }

    const selected = selectCaptionTrack(captionTracks);
    if (!selected) return null;

    const json3 = await fetchCaptionJSON3(selected.track.base_url);
    const rawText = json3EventsToText(json3.events);

    if (!rawText || rawText.length < CONFIG.MIN_TRANSCRIPT_LENGTH) {
      failureCache.set(failKey, true, CONFIG.CACHE_FAILURE_TTL);
      return null;
    }

    const cleaned = cleanTranscriptText(rawText);
    const finalText = deduplicateText(cleaned);

    const result = {
      text: finalText,
      source: 'transcript',
      metadata: {
        videoId,
        language: selected.language,
        isAutoGenerated: selected.isAutoGenerated,
        length: finalText.length,
        wordCount: finalText.split(/\s+/).filter(Boolean).length,
        fetchedAt: new Date().toISOString(),
      },
    };

    transcriptCache.set(videoId, result, CONFIG.CACHE_TTL);
    return result;

  } catch (error) {
    failureCache.set(failKey, true, CONFIG.CACHE_FAILURE_TTL);
    return null;
  }
}

// LECTURE CONTENT FETCHING AND ASSESSMENT
export async function getLectureContent(lecture) {
  const result = {
    lectureId: lecture.lectureId,
    lectureTitle: lecture.lectureTitle,
    text: '',
    source: 'unavailable',
    metadata: {},
  };

  if (lecture.lectureUrl) {
    const transcript = await fetchTranscriptSafe(lecture.lectureUrl);
    if (transcript) {
      result.text = transcript.text;
      result.source = 'transcript';
      result.metadata = transcript.metadata;
      return result;
    }
  }

  const desc = lecture.lectureDescription?.trim() ?? '';
  if (desc.length >= CONFIG.MIN_DESCRIPTION_LENGTH) {
    result.text = desc;
    result.source = 'description';
    result.metadata = {
      length: desc.length,
      wordCount: desc.split(/\s+/).filter(Boolean).length,
    };
    return result;
  }

  return result;
}

function assessContent(contentParts, wordLimit) {
  let totalWords = 0;
  for (const part of contentParts) {
    totalWords += part.text.split(/\s+/).filter(Boolean).length;
  }

  return {
    parts: contentParts,
    totalWords,
    needsSummarization: totalWords > wordLimit,
  };
}

export async function getChapterContent(chapter) {
  const lectures = chapter.chapterContent ?? [];
  const lectureStatuses = [];
  const contentSources = { transcript: 0, description: 0, unavailable: 0 };

  const tasks = lectures.map(lec => () => getLectureContent(lec));
  const results = await parallelLimit(tasks, CONFIG.CONCURRENT_LIMIT);

  const contentParts = [];

  for (let i = 0; i < results.length; i++) {
    const settled = results[i];
    const lec = lectures[i];

    if (settled.status === 'rejected') {
      lectureStatuses.push({
        lectureId: lec.lectureId,
        lectureTitle: lec.lectureTitle,
        source: 'unavailable',
        error: settled.reason?.message,
      });
      contentSources.unavailable++;
      continue;
    }

    const res = settled.value;

    lectureStatuses.push({
      lectureId: res.lectureId,
      lectureTitle: res.lectureTitle,
      source: res.source,
      metadata: res.metadata,
    });

    contentSources[res.source] = (contentSources[res.source] ?? 0) + 1;

    if (res.source !== 'unavailable' && res.text) {
      contentParts.push({
        lectureTitle: res.lectureTitle,
        text: res.text,
        source: res.source,
        metadata: res.metadata,
      });
    }
  }

  const { parts, totalWords, needsSummarization } = assessContent(contentParts, CONFIG.WORD_LIMIT);

  const fullContent = parts.length
    ? `Chapter: ${chapter.chapterTitle}\n\n` +
      parts.map(p => `--- Lecture: ${p.lectureTitle} ---\n${p.text}`).join('\n\n')
    : '';

  return {
    content: fullContent,
    contentParts: parts,
    lectureStatuses,
    contentSources,
    hasContent: fullContent.length > 100,
    needsSummarization,
    metadata: {
      totalLectures: lectures.length,
      processedLectures: parts.length,
      totalWords,
      truncated: false,
    },
  };
}

export function getCacheStats() {
  return {
    transcripts: { size: transcriptCache.size(), maxSize: CONFIG.CACHE_MAX_SIZE },
    failures: { size: failureCache.size(), maxSize: CONFIG.CACHE_MAX_SIZE },
  };
}

export function clearCache() {
  transcriptCache.clear();
  failureCache.clear();
  logger?.info?.('YouTube service caches cleared');
}

export function clearFailureCache() {
  failureCache.clear();
  logger?.info?.('YouTube failure cache cleared');
}

export default {
  extractVideoId,
  fetchTranscriptSafe,
  getLectureContent,
  getChapterContent,
  getCacheStats,
  clearCache,
  clearFailureCache,
};